[package]
name = "apis"
version = "0.0.14"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"

[lib]
name = "apis"

# remote dependencies
[dependencies]
num = "0.1.*"

#bit-set = "0.4.*"
#bit-vec = "0.4.*"
# temporary local fork for lazy_static bump
colored = { version = "1.*", git = "git://github.com/spearman/colored.git", branch = "bump-lazy_static" }
either = "1.*"
escapade = "0.0.*"
log = "0.4.*"
# temporary local fork for log update
simplelog = { version = "0.4.*", git = "git://github.com/spearman/simplelog.rs.git", branch = "log-update" }
smallvec = "0.6.*"
vec_map = "0.8.*"

# local dependencies
[dependencies.enum-unitary]
version = "0.1.*"
git = "git://github.com/spearman/enum-unitary.git"

[dependencies.macro-machines]
version = "0.2.*"
git = "git://github.com/spearman/macro-machines.git"
#path = "../macro-machines"

[dependencies.unbounded-spsc]
version = "0.1.*"
git = "git://github.com/spearman/unbounded-spsc.git"

# dev dependencies
[dev-dependencies]
mock = { path = "./mock/" }

# enum_unitary support
macro-attr = "0.2.*"
enum_derive = "0.1.*"

unwrap = "1.*"
rand = "0.4.*"
glium = "0.19.*"
