[package]
name = "apis"
version = "0.2.0"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"

[lib]
name = "apis"

[dependencies]
# unpublished upstream dependency update
colored = { version = "1.*", git = "git://github.com/mackwic/colored.git" }
either = "1.*"
escapade = "0.0.*"
log = "0.4.*"
num-traits = "0.2.*"
smallvec = "0.6.*"
vec_map = "0.8.*"

# local dependencies
enum-unitary = "0.3.*"
macro-machines = "0.8.*"
unbounded-spsc = "0.1.*"

# dev dependencies
[dev-dependencies]
mock = { path = "./mock/" }

glium = "0.20.*"
rand = "0.4.*"
simplelog = "0.5.*"
unwrap = "1.*"
