[package]
name = "apis"
version = "0.0.17"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"

[lib]
name = "apis"

# remote dependencies
[dependencies]
#bit-set = "0.4.*"
#bit-vec = "0.4.*"
# unpublished upstream dependency update
colored = { version = "1.*", git = "git://github.com/mackwic/colored.git" }
either = "1.*"
escapade = "0.0.*"
log = "0.4.*"
num = "0.1.*"
smallvec = "0.6.*"
vec_map = "0.8.*"

# local dependencies
[dependencies.enum-unitary]
version = "0.1.*"
git = "git://github.com/spearman/enum-unitary.git"

[dependencies.macro-machines]
version = "0.7.*"
git = "git://github.com/spearman/macro-machines.git"
#path = "../macro-machines"

[dependencies.unbounded-spsc]
version = "0.1.*"
git = "git://github.com/spearman/unbounded-spsc.git"

# dev dependencies
[dev-dependencies]
mock = { path = "./mock/" }

glium = "0.20.*"
rand = "0.4.*"
simplelog = "0.5.*"
unwrap = "1.*"

# enum_unitary support
macro-attr = "0.2.*"
enum_derive = "0.1.*"
