[package]
name = "apis"
version = "0.4.5"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"
description = "Reactive, session-oriented, asynchronous process-calculus framework"
repository = "https://github.com/spearman/apis"
readme = "README.md"
edition = "2018"

[lib]
name = "apis"

[dependencies]
colored = "2.*"
either = "1.*"
enum-iterator = "0.7.*"  # required by enum-unitary
log = "0.4.*"
marksman_escape = "0.1.*"
num-traits = "0.2.*"
smallvec = "1.*"
vec_map = "0.8.*"

# local dependencies
enum-unitary = "0.4.*"
macro-machines = "0.10.*"
unbounded-spsc = { version = "0.1.*", git = "https://github.com/spearman/unbounded-spsc.git" }

# dev dependencies
[dev-dependencies]
glium = "0.28.*"
rand = "0.7.*"
simplelog = "0.8.*"

[features]
# The reason we do this is because doctests don't get cfg(test) See:
# https://github.com/rust-lang/rust/issues/45599
test = []
