[package]
name = "apis"
version = "0.2.1"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"
description = "Reactive, session-oriented, asynchronous process-calculus framework"
repository = "https://github.com/spearman/apis"
readme = "README.md"

[lib]
name = "apis"

[dependencies]
colored = "1.*"
either = "1.*"
escapade = "0.0.*"
log = "0.4.*"
num-traits = "0.2.*"
smallvec = "0.6.*"
vec_map = "0.8.*"

# local dependencies
enum-unitary = "0.3.*"
macro-machines = "0.8.*"
unbounded-spsc = "0.1.*"

# dev dependencies
[dev-dependencies]
mock = { version = "0.1.0", path = "./mock/" }

glium = "0.20.*"
rand = "0.4.*"
simplelog = "0.5.*"
unwrap = "1.*"
